version: '3'
services:
  executor:
    build:
      context: .
      dockerfile: ExecutorDockerfile
    container_name: executor

  querier:
      build:
        context: .
        dockerfile: QuerierDockerfile
      container_name: querier

  receiver:
      build:
        context: .
        dockerfile: ReceiverDockerfile
      container_name: receiver
